apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: deployment-frontend:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription
  template:
    metadata:
      labels:
        app: prescription
    spec:
      containers:
      - name: prescription
        image: deployment-prescription:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: deployment-user:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: deployment-database:latest
        ports:
        - containerPort: 5432
        imagePullPolicy: Never

