# deployment/docker-compose.override.yml
version: "3.8"

services:
  vault:
    volumes:
      - ../secrets/vault/config:/vault/config
      - ../secrets/vault/policies:/vault/policies
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    command: "server"
  database:
    build:
      target: development
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=prescribe
  user:
    build:
      target: base
    environment:
      - NODE_ENV=development
      - ROLE_ID=${ROLE_ID}
      - SECRET_ID=${SECRET_ID}
    volumes:
      - ../backend/services/user/:/app
    command: "npm run dev"
  prescription:
    build:
      target: base
    environment:
      - NODE_ENV=development
      - ROLE_ID=${ROLE_ID}
      - SECRET_ID=${SECRET_ID}
    volumes:
      - ../backend/services/prescription/:/app
    command: "npm run dev"
  frontend:
    build:
      target: base
    environment:
      - NODE_ENV=development
    volumes:
      - ../frontend/app:/app
    command: "npm run dev"

volumes:
  database:
  vault-file:
  vault-logs:
