# deployment/docker-compose.prod.yml
version: "3.8"

services:
  vault:
    volumes:
      - ../secrets/vault/config:/vault/config
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    command: "server"
  database:
    build:
      target: base
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=prescribe
  user:
    build:
      target: production
    environment:
      - NODE_ENV=production
    command: "npm run start"
  prescription:
    build:
      target: production
    environment:
      - NODE_ENV=production
    command: "npm run start"
  frontend:
    build:
      target: production
    command: "npm run start"

volumes:
  database:
  vault-file:
  vault-logs:
