import localFont from "next/font/local";
import "./globals.css";

const sfProDisplay = localFont({
  src: "/fonts/SF-Pro-Display-Regular.otf",
  weights: [400],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sfProDisplay.className}>{children}</body>
    </html>
  );
}
